# Generated by Django 3.2.1 on 2021-05-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_course_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructer',
            new_name='Instructor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='instructer',
            new_name='instructor',
        ),
    ]
